# Generated by Django 3.0.5 on 2020-04-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_pre_Img',
            field=models.ImageField(default='default_incomplete.png', upload_to='before_service/'),
        ),
    ]
