# Generated by Django 3.0.3 on 2020-04-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_service_service_pre_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='complete_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='service_post_Img',
            field=models.ImageField(default='default_incomplete.png', upload_to='after_service/'),
        ),
    ]
