# Generated by Django 3.0.3 on 2020-04-24 14:38

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_service_service_pre_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=django_google_maps.fields.GeoLocationField(default='38.685516,-101.073324', max_length=100),
            preserve_default=False,
        ),
    ]
