# Generated by Django 3.0.3 on 2020-04-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20200427_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='complete_info',
            field=models.TextField(default='Service Completed'),
        ),
    ]
