# Generated by Django 3.0.5 on 2020-05-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_service_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
