# Generated by Django 3.0.5 on 2020-05-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_service_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
