# Generated by Django 3.0.6 on 2020-05-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20200519_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_mosquitokilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spray_used', models.CharField(max_length=200)),
                ('quantity_applied', models.IntegerField()),
                ('eliminated_standing_water', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('natural_repallant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('repallant_name', models.CharField(max_length=200)),
                ('other_info', models.TextField(default='Service Completed')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.service')),
            ],
        ),
    ]
