# Generated by Django 3.0.6 on 2020-05-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_feedback_mosquitokilling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='complete_info',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_post_Img',
        ),
        migrations.AddField(
            model_name='feedback_mosquitokilling',
            name='service_post_Img',
            field=models.ImageField(default='default_incomplete.png', upload_to='after_service/'),
        ),
    ]
