# Generated by Django 3.0.6 on 2020-05-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_auto_20200520_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='categories',
        ),
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.CharField(choices=[('Cleaning of River', 'Cleaning of River'), ('Plantation of Trees', 'Plantation of Trees'), ('Maintenance of an Area', 'Maintenance of an Area'), ('Mosquito-Killing', 'Mosquito-Killing')], default='Mosquito-Killing', max_length=50),
        ),
    ]
