# Generated by Django 3.0.6 on 2020-05-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20200520_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=models.CharField(choices=[('Pond Cleaning', 'Pond Cleaning'), ('Tree Planting', 'Tree Planting'), ('Maintenance of an Area', 'Maintenance of an Area'), ('Mosquito-Killing', 'Mosquito-Killing')], default='Mosquito-Killing', max_length=50),
        ),
        migrations.CreateModel(
            name='completion_treeplantation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_used', models.CharField(default='Not Used', max_length=100)),
                ('plant_variety', models.CharField(max_length=100)),
                ('water_quantity', models.IntegerField()),
                ('depth_dug', models.IntegerField()),
                ('residential_obstruction', models.TextField(default='No Obstruction caused to any residential property')),
                ('other_info', models.TextField(default='Service Completed')),
                ('service_post_Img', models.ImageField(default='default_incomplete.png', upload_to='after_service/')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feed.service')),
            ],
        ),
        migrations.CreateModel(
            name='completion_pondcleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drainage_done', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('pond_net_used', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('automatic_skimmer', models.CharField(max_length=100)),
                ('vaccum', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('beneficial_bacteria', models.CharField(max_length=100)),
                ('algae_treatment', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('other_info', models.TextField(default='Service Completed')),
                ('service_post_Img', models.ImageField(default='default_incomplete.png', upload_to='after_service/')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feed.service')),
            ],
        ),
        migrations.CreateModel(
            name='completion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_info', models.TextField(default='Service Completed')),
                ('service_post_Img', models.ImageField(default='default_incomplete.png', upload_to='after_service/')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feed.service')),
            ],
        ),
    ]
